version: '3.9'
services:
  database:
    container_name: iot_noise_backend_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234@
